### ISSUE TITLE
ImportError: cannot import name 'utc' from 'django.utils.timezone'

### ISSUE THREAD

**Issue by under-script** [buurak/django_websocket#1]
ImportError: cannot import name 'utc' from 'django.utils.timezone' (/home/user/PycharmProjects/django_websocket/env/lib/python3.11/site-packages/django/utils/timezone.py)

**Comment by under-script** [comment]
sorry

**Comment by under-script** [comment]
[requirements.txt](https://github.com/user-attachments/files/17268626/requirements.txt)
Removed packages' versions and re-installed them all.

**Comment by buurak** [comment]
Thanks for contribution, merged already

**Comment by under-script** [comment]
> Thanks for contribution, merged already

My pleasure
